Userのログイン機能の設計
dev-sota/going-to-go-example pull request #3
Opened 2021-02-02 03:51 UTC by dev-sota

## 該当イシュー
#2 

## 外部仕様の変更点
(フロントエンド の人に説明する必要がある場合)

## 内部仕様の変更点
(パフォーマンス・ロジックの変更を行った場合)

## 動作を保証するためのテストケースの詳細
- rspecのテストケース
- エンドツーエンドテストケース

2021-02-02 06:43 UTC, dev-sota commented on docs/features/users/create.md
> +- Usecase外部から呼び出されることはないため、privateな関数として実装し、Addメソッドから呼び出す。
bcryptで一行で済む処理なので、関数化しなくてもよいかも

2021-02-02 06:45 UTC, dev-sota commented on docs/features/users/login.md
> +- Usecase外部から呼び出されることはないため、privateな関数として実装し、Addメソッドから呼び出す。
エンコードと同じく

2021-02-02 06:51 UTC, dev-sota commented on docs/features/users/login.md
> +- `github.com/go-chi/jwtauth`を使用し、JWTを発行して、レスポンスとして返す。
この場合、JWT発行ロジックをusecaseに実装するべき...？

2021-02-02 08:02 UTC, dev-sota commented on docs/features/users/auth.md
> +- トークン情報(user_id)からユーザー検証する
Findメソッドを使って、user_idがDBに存在するか確認しようと思いましたが、
JWTの場合は署名の検証処理だけでよい？気がしていますが、あっていますか？

2021-02-02 08:26 UTC, yamad07 reviewed
こちら3点ほどコメントしました！確認おねがいいたします！

2021-02-02 08:26 UTC, yamad07 commented on docs/features/users/auth.md
> +- トークン情報(user_id)からユーザー検証する
ああ、これは議論が必要な部分ですが、結論からいうとmiddleware内でUserが存在するかどうかも検証した方が良いかな？と思っています！
認証が必要なエンドポイントに対しては、
1. ハンドラー側でuser_idをcontextから取得
2. user_idをusecaseのinputに渡してusecaseを実行
みたいな形になるので、Userが存在するかどうかのロジックがハンドラーやusecaseに散らばるのはあまりよくないかも？と思いました！
実装方法としては、おそらくuserのidをもとにUserをfindするユースケースみたいなのを実装して、そいつをmiddlewareに渡して(他のハンドラーのように)、検証するのが良さそうかな？と思います！

2021-02-02 08:26 UTC, yamad07 commented on docs/features/users/create.md
> +- Usecase外部から呼び出されることはないため、privateな関数として実装し、Addメソッドから呼び出す。
こちらはいくつかのアプローチがあるんですが、よくやるのは特定のロジックを一つのパッケージとしてまとめる、みたいなやつで、
```
pkg/password/pasword.go
```
みたいなディレクトリを切って、ここに暗号化とか検証とかのロジックを全て凝集して、usecaseはそのpkg経由で`password.Encrypt("password")`とか、`password.Authorize("password", "encrypred_password)` みたいな形で呼び出すと、
1. Usecaseが純粋なビジネスロジックだけに集中できるようになる
2. パスワードに関する仕様が一箇所にまとまるのでキャッチアップしやすい。
3. ユニットテストがかなり書きやすくなる
という点で結構使ってますね。
ただ、実装コストは少しかかってしまうデメリットはあります。

---
あまり頻発しないですが、railsのdeviceで実装されたパスワードのロジックをgoでこじ開けたいみたいなときに、それ専用のpkgを作ったりとかを前したので、それを参考までに貼っておきます！！

https://github.com/ispec-inc/bewin-monorepo/tree/stg/admin/pkg/devise

2021-02-02 08:26 UTC, yamad07 commented on docs/features/users/login.md
> +- `github.com/go-chi/jwtauth`を使用し、JWTを発行して、レスポンスとして返す。
これ、jwt発行ロジックはユースケース側の方がよいかな、と思いますね。
パスワードと同様にこれも何かしらのパッケージに切り出すのが良いかなと思っていますが、パスワードと違うのは、jwtの生成にuser_idが必要なので、ビジネスロジックに少し噛んでいる部分があるという点ですね。

---
パッと思いついた具体的な実装案としては、ドメイン知識があるという部分を考慮してpkgとして実装せず、値オブジェクト (DDDで出てくるやつです) として`pkg/value/token.go`みたいな感じで実装をして

```
tkn = value.NewToken(user_id)
```
みたいな感じにすると、トークンの生成ロジックをうまく隠蔽してusecaseを組み立てられるので、よいかな？と思いました！

2021-02-03 01:02 UTC, dev-sota commented on docs/features/users/auth.md
> +**`cmd/api/server/middleware/auth.go`**
middleware内の実装（メソッド数等）が、いまいち確定しないのでファイル名にしました。
実装しながら、docと合わせて適宜変更させてもらえると嬉しいです。

2021-02-03 01:10 UTC, yamad07 approved these changes
LGTMです！こちらで進めてください！

2021-02-05 10:38 UTC, dev-sota commented on src/user/usecase.go
> +	if aerr == nil {
このエラーハンドリングは見直します

2021-02-05 10:38 UTC, dev-sota commented on pkg/value/token.go
> +func NewToken(user_id int64) (Token, apperror.Error) {
値オブジェクトこんな感じで合ってます？

2021-02-05 10:40 UTC, dev-sota commented on docs/features/users/auth.md
> +    - ユーザー検証
doc見直しました。
来週あたりから実装しようと思います。

2021-02-08 03:46 UTC, dev-sota commented on pkg/value/claims.go
> +	UserID int64 `json:"uid"`
jwt.Parse時にuidがfloat64になってしまうため、Claims作成しました。

2021-02-08 03:50 UTC, dev-sota commented on cmd/api/middleware/auth.go
> +		claims, err := verifySignature(str)
署名検証と有効期限検証

2021-02-08 03:50 UTC, dev-sota commented on cmd/api/middleware/auth.go
> +		_, aerr := m.usecase.Find(inp)
ユーザー検証

2021-02-08 08:35 UTC, dev-sota commented on src/user/usecase.go
> +	if (res != model.User{}) {
テスト用にエラーハンドリングを変更しましたが、
これだと網羅できていないと思うので、
`if aerr != "recode not found"`
のようにエラーメッセージに応じて、分岐したい。
(メールアドレスが事前に登録されていないか確認したいので、
recode not found 時を正常系にしたい)

2021-02-08 08:36 UTC, dev-sota commented on src/user/usecase.go
> +	if (res != model.User{}) {
どうやって照合するかに悩んでいます。

2021-02-08 08:45 UTC, dev-sota commented on src/user/usecase_test.go
> +			out, aerr := u.Add(c.inp)
パスワード暗号化ロジックがあるとテストで落ちてしまう

2021-02-09 01:50 UTC, yamad07 requested changes
何点かコメントさせていただきました！確認の方お願いいたします！
ちょっとユースケースのテストで落ちてしまう原因がわからなかったので、結果の画面とかを共有してもらえると嬉しいです！

2021-02-09 01:50 UTC, yamad07 commented on cmd/api/adapter/user/handler.go
> +		Password: request.Password,
このドメインモデルの責務は、本来「ユーザー」を示すべきかな、と思うんですが、このようにパラメータみたいな使い方をしてしまうとユーザーのドメインモデルとして期待されている使い方から外れてるかも？と思いました！
やるなら、
1.  `domain/value/login_param.go`として実装し、そこの中にもしバリデーションのロジックがあるなら含むように実装をする。
2. そもそもmodelを経由せず、usecaseのinputに`Email`を`Password`を持たせる

とかすると、責務とその使い方が良い感じにマッチしてよいかな？と思いました！

2021-02-09 01:50 UTC, yamad07 commented on cmd/api/middleware/auth.go
> +		ctx = context.WithValue(ctx, "uid", claims.UserID)
これ、100%好みの問題なんですけど、せっかく `usecase.Find`で `User`が返ってきてるので、そのモデルを使って、
```
usr,  aerr := m.usecase.Find(inp)
```
で受け取って、
```
ctx = context.WithValue(ctx, "uid", usr.ID)
```
ってやるのが僕の好みです笑

今回の場合だったら、もし46行目で「取得できなかった(user_idに該当するUserがいなかった)のになぜかerrが返ってきてなかった」みたいなバグが起きていたときに、早期にバグを発見しやすいかも、と思ったりもしてます！

2021-02-09 01:50 UTC, yamad07 commented on docs/features/users/auth.md
> +    - ユーザー検証
よいですね！！

2021-02-09 01:50 UTC, yamad07 commented on pkg/infra/dao/user_test.go
> +func TestUserDao_FindByEmail(t *testing.T) {
テーブル駆動テスト、完璧ですね

2021-02-09 01:50 UTC, yamad07 commented on pkg/password/password.go
> +		return apperror.New(apperror.CodeError, err)
こういうpkg系は、極力外部ライブラリのように公開しても問題ないくらいの形で実装されているのがよいかな、と個人的には思っています。
なので、apperrorは内部パッケージなので、goの標準のerrorに依存するように実装されている方がよいかな？と思いました！
presenterのパッケージのように、apperrorに依存せざるを得ないもの以外は、極力apperror等の内部のものを呼ばないようにして欲しいです！

2021-02-09 01:50 UTC, yamad07 commented on pkg/value/claims.go
> +	UserID int64 `json:"uid"`
めちゃくちゃよいですね、ここにclaimに関する情報が凝集されていてわかりやすいです！

2021-02-09 01:50 UTC, yamad07 commented on src/user/usecase.go
> +	if (res != model.User{}) {
あ、それで言うと、`apperror`パッケージの`Code`を使うと良い感じに実装できるかもです。
https://github.com/dev-sota/going-to-go-example/blob/main/pkg/apperror/error.go#L14
gorm側で、Userが存在しなかった場合に、NotFoundのCodeを入れてapperror.Errorを返すようにしてげれば、
```
if aerr.Code() == apperror.CodeNotFound
```
みたいな感じでエラーのハンドリングができます！

2021-02-09 01:50 UTC, yamad07 commented on src/user/usecase_test.go
> +			out, aerr := u.Add(c.inp)
あれ、これって原因わかります、、、？

2021-02-09 02:07 UTC, dev-sota commented on src/user/usecase_test.go
> +			um.EXPECT().Create(&c.inp.User).Return(aerr)
![スクリーンショット 2021-02-09 10 58 48](https://user-images.githubusercontent.com/34063296/107305551-89a08780-6ac6-11eb-93a9-a8fb978b4a68.png)

この部分でエラーが発生してしまうのですが、パスワードが暗号化されてしまいます。

2021-02-09 02:18 UTC, yamad07 reviewed
あまり良い手立てが思いついてないんですが、コメントしました！

2021-02-09 02:18 UTC, yamad07 commented on src/user/usecase_test.go
> +			um.EXPECT().Create(&c.inp.User).Return(aerr)
ああ、なるほどです、、、この予期できない系のやつの手立てとしては、
1. 予期できない値を返すメソッドを持っている構造体をinterfaceにして、test用のpasswordのパッケージをDIする
2. gomock.Any()を使ったり、Exactlyの条件を緩めにする(idが一致していればOKとか)

などですが、今回は一旦1の方で実装してみてもよいかも？です！！

2021-02-09 04:54 UTC, dev-sota commented on pkg/infra/dao/error.go
> +	case gorm.ErrRecordNotFound.Error():
errだと条件に引っかからなかったので、err.Error()に変更しました。

2021-02-09 04:55 UTC, dev-sota commented on pkg/infra/dao/error.go
> +	switch errstr {
errだと条件に引っかからなかったので、err.Error()に変更しました。

2021-02-09 09:52 UTC, dev-sota commented on src/user/usecase_test.go
> +			um.EXPECT().Create(gomock.Any()).Return(aerr).Do(func(usr *model.User) {
1. 予期できない値を返すメソッドを持っている構造体をinterfaceにして、test用のpasswordのパッケージをDIする
2. gomock.Any()を使ったり、Exactlyの条件を緩めにする(idが一致していればOKとか)

2021-02-10 01:40 UTC, dev-sota commented on src/user/usecase_test.go
> +			um.EXPECT().Create(gomock.Any()).Return(aerr).Do(func(usr *model.User) {
1の実装も今後必要になりそうなので挑戦してみます！

2021-02-11 01:14 UTC, dev-sota commented on src/user/usecase_test.go
> +	hashed_password, err := password.Encrypt(raw_password)
ログインの方はテストデータを事前に準備しておくことで回避できました。

2021-02-11 03:52 UTC, dev-sota commented on src/user/usecase_test.go
> +			um.EXPECT().Create(gomock.Any()).SetArg(0, c.inp.User).Return(aerr)
こんな形でSetArgで参照渡ししつつ、passwordのロジックを隠蔽して実装できました。

2021-02-11 13:44 UTC, dev-sota commented on src/user/usecase_test.go
> +			um.EXPECT().Create(gomock.Any()).Return(aerr).Do(func(usr *model.User) {
1の方も調査してみました！
https://stackoverflow.com/questions/66093942/go-unit-testing-bcrypt

2021-02-12 01:31 UTC, yamad07 reviewed
基本的にはLGTMです！！
一点だけ、気になったので確認いただけると嬉しいです！

2021-02-12 01:31 UTC, yamad07 commented on pkg/infra/dao/error.go
> +	switch errstr {
ん、、これ分岐するはずですね、、
apperrorではなくgormから直接帰ってきたerrであれば、分岐するはずですが、
分岐しなかったときにerrの型がどう帰ってきてるかを一旦見てもらってもよいですかね、、？

2021-02-12 03:07 UTC, dev-sota commented on pkg/infra/dao/error.go
> +	"gorm.io/gorm"
これでした...笑

2021-02-12 04:21 UTC, yamad07 commented on pkg/infra/dao/error.go
> +	"gorm.io/gorm"
ああ、すみません、、、笑
ありがとうございます！！

2021-02-12 04:21 UTC, yamad07 approved these changes
LGTMです！！めちゃ良い感じだと思います！！

2021-02-12 04:24 UTC, merged